
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  name = "github.com/awslabs/amazon-ecr-credential-helper"

[[constraint]]
  name = "github.com/cihub/seelog"

[[constraint]]
  name = "github.com/docker/go-units"

[[constraint]]
  name = "github.com/docker/libcompose"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-shlex"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  name = "github.com/go-ini/ini"

[[constraint]]
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/urfave/cli"

[[constraint]]
  name = "gopkg.in/yaml.v2"
